### ISSUE TITLE
AddVersion: Unable to check remote location of provided folder.

### ISSUE THREAD

**Issue by woznik** [CAST-Extend/com.castsoftware.aip.console.tools#10]
Hello
I have upgraded from  aip-console-tools-cli.jar Nov 2019 to the latest one by building a package from the master branch
When I use the same command to run the scan I obtain an error
```
2020-08-18 15:27:19.574 - INFO --- Searching for application 'webgoat' on AIP Console
2020-08-18 15:27:20.441 -ERROR --- Error occurred while attempting to upload the given file.

com.castsoftware.aip.console.tools.core.exceptions.UploadException: Unable to check remote location of provided folder.
   at com.castsoftware.aip.console.tools.core.services.UploadServiceImpl.uploadFileAndGetSourcePath(UploadServiceImpl.java:100) ~[aip-console-tools-core-1.18.0-SNAPSHOT.jar!/:1.18.0-SNAPSHOT]
   at com.castsoftware.aip.console.tools.commands.AddVersionCommand.call(AddVersionCommand.java:147) [classes!/:1.18.0-SNAPSHOT]
   at com.castsoftware.aip.console.tools.commands.AddVersionCommand.call(AddVersionCommand.java:31) [classes!/:1.18.0-SNAPSHOT]
   at picocli.CommandLine.execute(CommandLine.java:1173) [picocli-3.9.6.jar!/:3.9.6]
   at picocli.CommandLine.access$800(CommandLine.java:141) [picocli-3.9.6.jar!/:3.9.6]
   at picocli.CommandLine$RunLast.handle(CommandLine.java:1367) [picocli-3.9.6.jar!/:3.9.6]
   at picocli.CommandLine$RunLast.handle(CommandLine.java:1335) [picocli-3.9.6.jar!/:3.9.6]
   at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243) [picocli-3.9.6.jar!/:3.9.6]
   at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526) [picocli-3.9.6.jar!/:3.9.6]
   at picocli.CommandLine.parseWithHandler(CommandLine.java:1465) [picocli-3.9.6.jar!/:3.9.6]
   at com.castsoftware.aip.console.tools.AipIntegrationCliMain.run(AipIntegrationCliMain.java:44) [classes!/:1.18.0-SNAPSHOT]
   at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
   at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
   at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
   at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
   at com.castsoftware.aip.console.tools.AipIntegrationCliMain.main(AipIntegrationCliMain.java:33) [classes!/:1.18.0-SNAPSHOT]
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
   at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
   at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [aip-console-tools-cli.jar:1.18.0-SNAPSHOT]
   at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [aip-console-tools-cli.jar:1.18.0-SNAPSHOT]
   at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [aip-console-tools-cli.jar:1.18.0-SNAPSHOT]
   at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [aip-console-tools-cli.jar:1.18.0-SNAPSHOT]
Caused by: com.castsoftware.aip.console.tools.core.exceptions.ApiCallException: Response code from API was unexpected : 412
Content was [{"arguments":[],"code":"invalidValue","defaultMessage":"must not be null","field":"root"}]
   at com.castsoftware.aip.console.tools.core.services.RestApiServiceImpl.exchangeForEntity(RestApiServiceImpl.java:276) ~[aip-console-tools-core-1.18.0-SNAPSHOT.jar!/:1.18.0-SNAPSHOT]
   at com.castsoftware.aip.console.tools.core.services.RestApiServiceImpl.exchangeForEntity(RestApiServiceImpl.java:240) ~[aip-console-tools-core-1.18.0-SNAPSHOT.jar!/:1.18.0-SNAPSHOT]
   at com.castsoftware.aip.console.tools.core.services.RestApiServiceImpl.postForEntity(RestApiServiceImpl.java:153) ~[aip-console-tools-core-1.18.0-SNAPSHOT.jar!/:1.18.0-SNAPSHOT]
   at com.castsoftware.aip.console.tools.core.services.UploadServiceImpl.uploadFileAndGetSourcePath(UploadServiceImpl.java:97) ~[aip-console-tools-core-1.18.0-SNAPSHOT.jar!/:1.18.0-SNAPSHOT]
   ... 23 common frames omitted
```

was there any change in CLI command usage?

Previosly I used:
```
java $JAVA_OPTS -jar aip-console-tools-cli.jar AddVersion --app-name=$CI_PROJECT_NAME --server-url=$CAST_CONSOLE_SRV_URL --apikey=$CAST_CONSOLE_TOKEN --file /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME.tar.gz --version-name=$CI_COMMIT_SHORT_SHA --auto-create --enable-security-dataflow
```

**Comment by woznik** [comment]
Just for impormation I use CastConsole 1.11 on the backend

**Comment by skn33** [comment]
hi, using the folder feature is introduced in Console 1.15, with 1.11 you need to continue use the zip files and upload

**Comment by woznik** [comment]
ok, I will change my scripts to use zip files, thannks
